name: Two Pipelines Example

on:
  push:
    branches:
      - main

jobs:
  first_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run First Pipeline
        run: |
          # Your first pipeline steps go here

  second_pipeline:
    needs: first_pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Second Pipeline
        run: |
          # Your second pipeline steps go here
