name: Aqua

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  aqua:
    name: Aqua scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Network Test
        run:  |
              # For Trivy artifact download:
              curl -vvv https://github.com/
              curl -vvv https://ghcr.io
              curl -vvv https://pkg-containers.githubusercontent.com
              # within EU
              curl -vvv https://api.eu-1.supply-chain.cloud.aquasec.com
              curl -vvv https://eu-1.api.cloudsploit.com
              curl -vvv https://scan.eu-1.codesec.aquasec.com
              curl -vvv https://connect.eu-1.codesec.aquasec.com

      - name: Run Aqua scanner
#        uses: docker://aquasec/aqua-scanner
        uses: docker://aquasec/aqua-scanner:v0.180.1
        with:
#          args: trivy fs --scanners config,vuln,secret .
          args: trivy fs --scanners misconfig,vuln,secret .
          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          # To enable SAST scanning, add: --sast
          # To enable reachability scanning, add: --reachability
          # To enable npm/dotnet/gradle non-lock file scanning, add: --package-json / --dotnet-proj / --gradle
        env:
#          AQUA_KEY: ${{ secrets.AQUA_KEY }}
#          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          AQUA_KEY: nouJFbPaVuXElxuXgeD9j8
          AQUA_SECRET: EhTdRr4vGI6NrsHptAj1A4kkYNCGl8bnSkR
          GITHUB_TOKEN: ${{ github.token }}
          AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
          CSPM_URL: https://eu-1.api.cloudsploit.com
          TRIVY_RUN_AS_PLUGIN: 'aqua'
          TRIVY_DEBUG: true
          # For http/https proxy configuration add env vars: HTTP_PROXY/HTTPS_PROXY, CA-CRET (path to CA certificate)
