name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types:
      - opened
      
jobs:
  checkout:
    name: Checkout1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup pipeline enforcer
        uses: aquasecurity/pipeline-enforcer-action@main
        with:
          aqua-key: ${{ secrets.AQUA_KEY }}
          aqua-secret: ${{ secrets.AQUA_SECRET }}

      - name: List files
        run:  pwd &&
              ls -l . &&
              ls -l / &&
              git config --global --add safe.directory /github/workspace

